### ISSUE TITLE
Artifact work post Roadmap Workshop

### ISSUE THREAD

**Issue by arouault** [VermontAHS/IEE-Modernization#27]
Answer the following questions:

**- What is our goal / what are we trying to accomplish in the next 2 weeks?**
- [x] Refine artifacts into a shareable, accessible format 
- [x] Ensure Roadmap reflects where VT wants to be in the next few weeks 
- [x] Use these as a tool for CMS comms 

**- How will we measure if this is successful (Acceptance Criteria)?**
- [x] Vermonters participate in the process of updating

**- What are the Concrete Next Steps?**
- [x] Timeline work 
- [x] North Star revisions (issue #32) 
- [x] Roadmap digitizing work 
- [x] Digitize photographs (parking lot, internal constraints, things from feasibility concerns, mitigation requirements (outside of roadmap)

Then: 
- Assign a Lead to this Work
- Add to Project Board in Flight
- Apply any appropriate labels

**Comment by amyashida** [comment]
Digitized artifacts here: 
- https://app.mural.co/t/gsa6/m/gsa6/1542652654147/523622f4c5838a667ea86961d9dfd88585072f44

Photos here: https://drive.google.com/drive/u/0/folders/1XDBDEhVVX63-sFzkYBfORcwe7NX51UfJ

**Comment by amyashida** [comment]
Timeline is here: https://app.mural.co/t/gsa6/m/gsa6/1542134269737/56b397722eaaceaa9f425e6679a15f8fe401dbbe
