### ISSUE TITLE
Develop Authentication Project Plan (One Pager)

### ISSUE THREAD

**Issue by arouault** [VermontAHS/IEE-Modernization#34]
Goal: 

- Clearly articulate plan for authentication project work with Vermont to inform Steering Committee Decisions

Success Criteria: 

- [x] 1. Collaboratively developed with Seamus, other stakeholders (Nava, C2)? 
- [x] 2. Clearly communicates plan for Authentication work 
- [x] 3. Clearly communicates 18F's role in that work 
- [ ] 4. Clearly communicates a timeline for the work

Next Steps: 

- [x] Draft authentication plan
- [x] Include relevant elements from cross-functional strategy documents
- [x] Share and edit with Seamus 
- [x] Review with Cass

**Comment by arouault** [comment]
Draft going here: https://docs.google.com/document/d/1Xvfex9MZammR9SZpppbd6mV7RhT1Ii9kKd7HP6nYdbI/edit

**Comment by arouault** [comment]
Note: structure differs from Strategy Template doc. Include sections above.

**Comment by arouault** [comment]
- [ ] Steven to share out Authentication Plan draft (current) with Seamus for edits

**Comment by stvnrlly** [comment]
@stvnrlly incorporate plan back into other existing docs

**Comment by arouault** [comment]
Here's the memo which will be whittled down by @apburnes https://docs.google.com/document/d/1I7rZ2BksJY3_WAohgFxzwtfau69vqmOcW3rHfWOezb8/edit
