### ISSUE TITLE
Customer Portal Phase 2 roadmap work

### ISSUE THREAD

**Issue by stvnrlly** [VermontAHS/IEE-Modernization#45]

**Comment by stvnrlly** [comment]
@amyashida to add more context here

**Comment by amyashida** [comment]
Answer the following questions:

**- What is our goal / what are we trying to accomplish in the next 2 weeks?**
CP roadmap is one place that clearly communicates
- [ ]  the order in which work is planned 
- [ ]  insight into what will happen over the next 6 months - 1 year to set up Phase 2 for success
- [ ]  a level of information that oversight bodies (Steering Committee, CMS, other stakeholders) feel comfortable with 

- [ ] the roadmap can be managed by Vermont

**- How will we measure if this is successful (Acceptance Criteria)?**
- [ ]  the roadmap has been reviewed by and is signed off on by major stakeholders

**- What are the Concrete Next Steps?**
- [ ] Amy to work with Thani, future product owner, and other stakeholders to review goals, format, and define near-term work
- [ ] convert existing documents into final format
- [ ] share out roadmap for feedback with needed stakeholders

Then: 
- Assign a Lead to this Work
- Add to Project Board in Flight
- Apply any appropriate labels

**Comment by amyashida** [comment]
This is partially blocked by wanting to loop in the future PO and technical stakeholders. Who will be in these roles has not been finalized. 

@arouault Is this blocked in any way by the program-level road mapping work?

**Comment by arouault** [comment]
- [ ] add remaining roadmap work tasks to Azure (technical review with Seamus, Steven, Emily)
